name: ci-cd test 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x , 16.x ]  # Usa entrambe le versioni

    steps:
      - uses: actions/checkout@v2
      - name: Usa Node.js in versione ${{ matrix.node-version }}
        uses: actions/setup-node@v1  # Usa la versione v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Aggiungi questa condizione

    steps:
      - uses: actions/checkout@v2

      - name: LogIn sul DockerHub
        uses: docker/login-action@v1  # Usa la versione v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push dell'Immagine
        uses: docker/build-push-action@v2
        with:
          context: .  
          file: Dockerfile
          push: true
          tags: raf593/libri-api
          